# Generated by Django 5.1.15 on 2026-05-04 05:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('book_type', models.CharField(choices=[('pdf', 'PDF'), ('print', '製本')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('no_paid', '未払い'), ('paid', '支払済み'), ('expired', '期限切れ'), ('ordered', '製本依頼済み')], default='no_paid', max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('sq_pay_id', models.CharField(blank=True, default='', max_length=255)),
                ('pdf_key', models.CharField(blank=True, default='', max_length=255)),
                ('pdf_exp', models.DateTimeField()),
                ('hair_color', models.CharField(choices=[('black', '黒'), ('dkbrown', '焦茶'), ('brown', '茶'), ('gold', '金'), ('rdbrown', '赤茶'), ('gray', 'グレー'), ('white', '白')], default='black', max_length=10)),
                ('skin', models.CharField(choices=[('white', '色白'), ('flesh', '肌色'), ('wheat', '小麦色'), ('brown', '褐色'), ('dark', 'ダーク')], default='flesh', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '05 books',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('post', models.CharField(blank=True, default='', max_length=10)),
                ('address', models.TextField()),
                ('mail_ok', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '01 buyers',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('logo', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '02 clients',
            },
        ),
        migrations.CreateModel(
            name='FacePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('hair', '髪'), ('eye', '目'), ('nose', '鼻'), ('mouth', '口')], default='hair', max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('angle', models.CharField(choices=[('front', '前'), ('45', '斜め'), ('side', '横'), ('back', '後ろ')], default='front', max_length=10)),
                ('img_path', models.CharField(blank=True, max_length=255)),
                ('sort', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '07 face parts',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField(default=0)),
                ('pattern', models.SmallIntegerField(default=0)),
                ('img_path', models.CharField(max_length=255)),
                ('angle', models.CharField(choices=[('front', '前'), ('45', '斜め'), ('side', '横'), ('back', '後ろ')], default='front', max_length=10)),
                ('cx', models.SmallIntegerField(default=0)),
                ('cy', models.SmallIntegerField(default=0)),
                ('size', models.SmallIntegerField(default=0)),
                ('offset', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '08 images',
            },
        ),
        migrations.CreateModel(
            name='PendingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '99 pending books',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ehon.book')),
            ],
            options={
                'verbose_name_plural': '09 answers',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehon.buyer'),
        ),
        migrations.AddField(
            model_name='book',
            name='eye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ehon.facepart'),
        ),
        migrations.AddField(
            model_name='book',
            name='hair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ehon.facepart'),
        ),
        migrations.AddField(
            model_name='book',
            name='mouth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ehon.facepart'),
        ),
        migrations.AddField(
            model_name='book',
            name='nose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ehon.facepart'),
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField(default=0)),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehon.book')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehon.image')),
            ],
            options={
                'verbose_name_plural': '06 book pages',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('prompt', models.TextField()),
                ('price_pdf', models.IntegerField(default=300)),
                ('price_print', models.IntegerField(default=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ehon.client')),
            ],
            options={
                'verbose_name_plural': '03 themes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.SmallIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehon.theme')),
            ],
            options={
                'verbose_name_plural': '04 questions',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ehon.theme'),
        ),
        migrations.AddField(
            model_name='book',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ehon.theme'),
        ),
    ]
