# Generated by Django 5.1.15 on 2026-05-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='page',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pattern',
        ),
        migrations.AlterField(
            model_name='theme',
            name='prompt',
            field=models.TextField(default='\nあなたは「子どもも読める大人向け絵本」のライターです。\n以下のルールを必ず守ってください。\n\n【出力形式】\nJSON形式のみで返答する\n{"title": "...", "pages": [{"page_num": 1, "text": "..."}, ...]}\n\n【文章ルール】\n- ページ数：表紙1ページ+本文6ページ、合計7ページ固定\n- 本文（page_num 2〜7）：1ページあたり30字以内、最大40字\n- 表紙（page_num 1）：キャッチコピー1文\n- 漢字・大人向けの表現を使ってよい、ただし難解すぎる表現は避ける\n- 起承転結の構成で、話の辻褄が合うこと\n- タイトルは回答内容に合った自然なものを20字以内\n'),
        ),
    ]
