# Generated by Django 5.1.15 on 2026-05-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0003_alter_theme_prompt_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': '90 answers'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '10 books'},
        ),
        migrations.AlterModelOptions(
            name='bookpage',
            options={'verbose_name_plural': '11 book pages'},
        ),
        migrations.AlterModelOptions(
            name='facepart',
            options={'verbose_name_plural': '20 face parts'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': '21 images'},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name_plural': '05 style'},
        ),
    ]
