# Generated by Django 5.1.15 on 2026-05-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0004_alter_answer_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='sq_pay_id',
            new_name='sp_pay_id',
        ),
    ]
