# Generated by Django 5.1.15 on 2026-05-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0005_rename_sq_pay_id_book_sp_pay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
