# Generated by Django 5.1.15 on 2026-05-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0006_question_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facepart',
            name='label',
        ),
        migrations.RemoveField(
            model_name='facepart',
            name='sort',
        ),
        migrations.AlterField(
            model_name='facepart',
            name='angle',
            field=models.CharField(choices=[('0', '0deg'), ('45', '45deg'), ('90', '90deg'), ('135', '135deg'), ('180', '180deg')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='angle',
            field=models.CharField(choices=[('0', '0deg'), ('45', '45deg'), ('90', '90deg'), ('135', '135deg'), ('180', '180deg')], default='0', max_length=10),
        ),
    ]
