# Generated by Django 5.1.15 on 2026-06-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0007_remove_facepart_label_remove_facepart_sort_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='cx',
            new_name='tilt',
        ),
        migrations.RemoveField(
            model_name='image',
            name='cy',
        ),
        migrations.RemoveField(
            model_name='image',
            name='offset',
        ),
        migrations.AlterField(
            model_name='book',
            name='hair_color',
            field=models.CharField(choices=[('#1a1a1a', '黒'), ('#3d1f0d', '焦茶'), ('#7b3f00', '茶'), ('#d4a017', '金'), ('#8b3a2a', '赤茶'), ('#808080', '灰色'), ('#f5f5f5', '白')], default='#1a1a1a', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='skin',
            field=models.CharField(choices=[('#fde8d0', '色白'), ('#f0c08a', '肌色'), ('#c8956c', '小麦色'), ('#8b5e3c', '褐色'), ('#4a2f1a', '色黒')], default='#f0c08a', max_length=10),
        ),
        migrations.AlterField(
            model_name='theme',
            name='prompt',
            field=models.TextField(default='\nあなたは「子どもも読める大人向け絵本」のライターです。\n以下のルールを必ず守ってください。\n\n【出力形式】\nJSON形式のみで返答する\n{"pages": [{"page_num": 1, "text": "..."}, ...]}\n\n【文章ルール】\n- ページ数：表紙1ページ+本文6ページ、合計8ページ固定\n- 本文（page_num 2〜7）：1ページあたり30字以内、最大40字\n- 表紙（page_num 1）：タイトル兼キャッチコピー1文\n- 背表紙（page_num 8）：「おわり」のみをセット\n- 漢字・大人向けの表現を使ってよい、ただし難解すぎる表現は避ける\n- 起承転結の構成で、話の辻褄が合うこと\n- タイトルは回答内容に合った自然なものを20字以内\n'),
        ),
    ]
