# Generated by Django 5.1.15 on 2026-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0008_rename_cx_image_tilt_remove_image_cy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ox',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='oy',
            field=models.SmallIntegerField(default=0),
        ),
    ]
