# Generated by Django 5.1.15 on 2026-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0009_image_ox_image_oy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookpage',
            old_name='page',
            new_name='spread',
        ),
        migrations.RenameField(
            model_name='bookpage',
            old_name='text',
            new_name='text1',
        ),
        migrations.AddField(
            model_name='bookpage',
            name='text2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
