# Generated by Django 5.1.15 on 2026-06-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0010_rename_page_bookpage_spread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facepart',
            name='angle',
            field=models.CharField(choices=[('0', '0'), ('45', '45'), ('90', '90'), ('135', '135'), ('180', '180')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='angle',
            field=models.CharField(choices=[('0', '0'), ('45', '45'), ('90', '90'), ('135', '135'), ('180', '180')], default='0', max_length=10),
        ),
    ]
