# Generated by Django 5.1.15 on 2026-06-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0011_alter_facepart_angle_alter_image_angle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='AnswerLog',
        ),
    ]
