# Generated by Django 5.1.15 on 2026-06-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0012_rename_answer_answerlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlog',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehon.book'),
        ),
    ]
