# Generated by Django 5.1.15 on 2026-06-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0013_alter_answerlog_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='hair_color',
        ),
        migrations.AlterField(
            model_name='book',
            name='hair',
            field=models.CharField(choices=[('#1a1a1a', '黒'), ('#3d1f0d', '焦茶'), ('#7b3f00', '茶'), ('#d4a017', '金'), ('#8b3a2a', '赤茶'), ('#808080', '灰色'), ('#f5f5f5', '白')], default='#1a1a1a', max_length=10),
        ),
    ]
