# Generated by Django 5.1.15 on 2026-07-01 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0015_rename_skin_book_skin_color_book_hair_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('hair', '髪色'), ('skin', '肌色')], default='hair', max_length=10)),
                ('label', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': '21 colors',
            },
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': '22 images'},
        ),
        migrations.AlterField(
            model_name='book',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ehon.buyer'),
        ),
        migrations.AlterField(
            model_name='book',
            name='eye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ehon.facepart'),
        ),
        migrations.AlterField(
            model_name='book',
            name='hair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ehon.facepart'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mouth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ehon.facepart'),
        ),
        migrations.AlterField(
            model_name='book',
            name='nose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ehon.facepart'),
        ),
        migrations.AlterField(
            model_name='book',
            name='hair_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ehon.colors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='skin_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ehon.colors'),
        ),
    ]
