# Generated by Django 5.1.15 on 2026-07-01 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0016_colors_alter_image_options_alter_book_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehon.image'),
        ),
    ]
