# Generated by Django 5.1.15 on 2026-07-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0017_alter_bookpage_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='price_print',
            new_name='price_soft',
        ),
        migrations.AddField(
            model_name='theme',
            name='price_hard',
            field=models.IntegerField(default=8000),
        ),
        migrations.AlterField(
            model_name='theme',
            name='prompt',
            field=models.TextField(default='\nあなたは「子どもも読める大人向け絵本」のライターです\n以下のルールを必ず守ってください\n\n【出力形式】\nJSON形式のみで返答する\n{"spreads": [{"sp_num": 1, "text1": "...", "text2": "..."}, ...]}\n見開きに対して2文セット\n\n【共通ルール】\n- ページ数：表紙+本文+背表紙の構成\n- JSON形式：見開き(sp_num)は、2ページをまとめる\n- 表紙（sp_num 0）：タイトル、15文字程度に簡潔にまとめる\n- 本文（sp_num 1~*）：1ページ20字程度の一言にまとめる\n- 背表紙（sp_num *+1）：「おわり」のみをセット\n- 漢字・大人向けの表現を使ってよい、ただし難解すぎる表現は避ける\n- 起承転結の構成で、話の辻褄が合うこと\n- 全回答を使う必要はないが、各ページの繋がりは大切\n- 回答が空の場合は、その項目を無視して作成すること\n- 句読点（、。）は使用せずに半角スペースを使う\n\n【テーマ毎のルール】\n- 8見開き(表紙、裏表紙は別）\n- text2は空文字 ※JSON形式は統一\n\n[タイトルの例]\n- ものづくりの少年から親へ\n- 愛情のバトンタッチ\n\n[本文の例]\n- ぼくは ものを作るのが好きだった（16文字）\n- うまくいかない日も 考え続けた（15文字）\n'),
        ),
    ]
