# Generated by Django 5.1.15 on 2026-07-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0018_rename_price_print_theme_price_soft_theme_price_hard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('soft', '小冊子'), ('hard', 'ハードカバー')], default='pdf', max_length=10),
        ),
    ]
