# Generated by Django 5.1.15 on 2026-07-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0019_alter_book_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facepart',
            name='angle',
        ),
        migrations.RemoveField(
            model_name='image',
            name='oy',
        ),
        migrations.AlterField(
            model_name='image',
            name='angle',
            field=models.SmallIntegerField(default=0),
        ),
    ]
