# Generated by Django 5.1.15 on 2026-07-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0020_remove_facepart_angle_remove_image_oy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facepart',
            name='is_turn',
            field=models.BooleanField(default=True),
        ),
    ]
