# Generated by Django 5.1.15 on 2026-07-07 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0021_facepart_is_turn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facepart',
            old_name='is_turn',
            new_name='eye_turn',
        ),
    ]
