# Generated by Django 5.1.15 on 2026-07-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0023_remove_client_api_key_client_user_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='chk_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='chk_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
