# Generated by Django 5.1.15 on 2026-07-31 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0024_client_chk_exp_client_chk_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name_plural': '30 coupons'},
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LkCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lk_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('exp_at', models.DateTimeField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehon.coupon')),
            ],
            options={
                'verbose_name_plural': '31 lock coupons',
            },
        ),
    ]
