# Generated by Django 5.1.15 on 2026-08-01 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0025_alter_coupon_options_alter_client_user_lkcoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='client',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='used_cnt',
        ),
        migrations.AddField(
            model_name='coupon',
            name='rest_cnt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ehon.theme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkcoupon',
            name='session',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
