# Generated by Django 5.1.15 on 2026-08-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0026_remove_coupon_client_remove_coupon_used_cnt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkcoupon',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkcoupon',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
