# Generated by Django 5.1.15 on 2026-08-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0027_lkcoupon_email_lkcoupon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkcoupon',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lkcoupon',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
