# Generated by Django 5.1.15 on 2026-08-06 02:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0028_alter_lkcoupon_email_alter_lkcoupon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='chk_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
