# Generated by Django 5.1.15 on 2026-08-12 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0029_alter_client_chk_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceGroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '21 face group name',
            },
        ),
        migrations.CreateModel(
            name='Subsc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.SmallIntegerField(default=3000)),
                ('base_cnt', models.SmallIntegerField(default=3)),
                ('add_cnt', models.SmallIntegerField(default=3)),
                ('add_price', models.SmallIntegerField(default=500)),
            ],
            options={
                'verbose_name_plural': '50 subsc',
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '30 books'},
        ),
        migrations.AlterModelOptions(
            name='bookpage',
            options={'verbose_name_plural': '31 book pages'},
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name_plural': '23 colors'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name_plural': '40 coupons'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': '13 images'},
        ),
        migrations.AlterModelOptions(
            name='lkcoupon',
            options={'verbose_name_plural': '41 coupons lock'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': '11 questions'},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name_plural': '12 style'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name_plural': '10 themes'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='theme',
        ),
        migrations.AddField(
            model_name='image',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ehon.client'),
        ),
        migrations.AddField(
            model_name='image',
            name='orig_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='eye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ehon.facepart'),
        ),
        migrations.AlterField(
            model_name='book',
            name='hair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ehon.facepart'),
        ),
        migrations.AlterField(
            model_name='book',
            name='hair_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ehon.colors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mouth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ehon.facepart'),
        ),
        migrations.AlterField(
            model_name='book',
            name='nose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ehon.facepart'),
        ),
        migrations.AlterField(
            model_name='book',
            name='skin_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ehon.colors'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='price_pdf',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='theme',
            name='price_soft',
            field=models.IntegerField(default=3500),
        ),
        migrations.CreateModel(
            name='ClientSubsc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_sub_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'アクティブ'), ('canceled', 'キャンセル'), ('past_due', '有効期限切れ')], default='active', max_length=15)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ehon.client')),
                ('subsc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ehon.subsc')),
            ],
            options={
                'verbose_name_plural': '51 client subsc',
            },
        ),
        migrations.AddField(
            model_name='theme',
            name='face_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ehon.facegroupname'),
        ),
        migrations.CreateModel(
            name='CouponDist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_cnt', models.SmallIntegerField(default=3)),
                ('client_subsc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehon.clientsubsc')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ehon.theme')),
            ],
            options={
                'verbose_name_plural': '52 coupon dist',
                'unique_together': {('client_subsc', 'theme')},
            },
        ),
        migrations.CreateModel(
            name='FaceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ehon.facepart')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehon.facegroupname')),
            ],
            options={
                'verbose_name_plural': '22 face group',
                'unique_together': {('group_name', 'part')},
            },
        ),
        migrations.CreateModel(
            name='ThemeImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ehon.image')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehon.theme')),
            ],
            options={
                'verbose_name_plural': '14 theme img',
                'unique_together': {('theme', 'img')},
            },
        ),
    ]
