# Generated by Django 5.1.15 on 2026-08-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0030_facegroupname_subsc_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsubsc',
            old_name='stripe_sub_id',
            new_name='sp_sub_id',
        ),
        migrations.RenameField(
            model_name='facegroup',
            old_name='group_name',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='subsc',
            old_name='stripe_price_id',
            new_name='sp_price_id',
        ),
        migrations.AlterUniqueTogether(
            name='facegroup',
            unique_together={('group', 'part')},
        ),
    ]
