# Generated by Django 5.1.15 on 2026-08-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0031_rename_stripe_sub_id_clientsubsc_sp_sub_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
