# Generated by Django 5.1.15 on 2026-08-18 09:24

from django.db import migrations


def update_status(apps, schema_editor):
    Book = apps.get_model('ehon', 'Book')
    Book.objects.filter(status='paid').update(status='stripe')

class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0032_client_is_free'),
    ]

    operations = [
      migrations.RunPython(update_status, migrations.RunPython.noop),
    ]

