# Generated by Django 5.1.15 on 2026-08-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0033_update_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubsc',
            name='sp_cust_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('stripe', 'Stripe購入'), ('paypay', 'PayPay購入'), ('coupon', 'クーポン使用')], default='stripe', max_length=10),
        ),
    ]
