# Generated by Django 5.1.15 on 2026-09-08 04:47

import apps.ehon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0035_answerlog_prev_at_answerlog_sel_at_answerlog_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='title_style',
            field=models.JSONField(blank=True, default=apps.ehon.models._title_style_default, null=True),
        ),
    ]
