# Generated by Django 5.1.15 on 2026-09-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehon', '0036_alter_theme_title_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
